pipeline:
  name: grant-microservice3
  identifier: grantmicroservice3
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: grant-microservice3
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  name: Git-Clone
                  identifier: GitClone
                  template:
                    templateRef: Git
                    versionLabel: v0.1.0
              - step:
                  type: Run
                  name: Prepare-Bootstrap
                  identifier: PrepareBootstrap
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine:latest
                    shell: Sh
                    command: |-
                      pwd
                      ls -la
                      sleep 10
                      cd devops-central
                      cp python.py ../
                      cp Dockerfile ../
                      cd ../../
                      ls -la                     
              - step:
                  type: Run
                  name: Mvn
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-amazoncorretto-17-al2023
                    shell: Sh
                    command: |-
                      java --version
                      mvn clean install -DskipTests
              - step:
                  name: docker
                  identifier: docker
                  template:
                    templateRef: Docker
                    versionLabel: v0.1.0
                    gitBranch: main       
    - stage:
        name: Approval
        identifier: Approval
        tags: {}
        template:
          templateRef: Approval
          versionLabel: v0.1.0
          gitBranch: main
    - stage:
        name: BlueGreen
        identifier: BlueGreen
        tags: {}
        template:
          templateRef: BlueGreen
          versionLabel: v0.1.0          
